[build]
  command = "yarn workspace site build"
  Functions = "netlify/functions/"
  publish = "site/public"

[dev]
  command = "yarn develop"

[[headers]]
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"